<li>
                  <a href="[field:arcurl/]" target="_blank" class="thumb"><img src="[field:litpic/]" /></a>
                  <span class="title"><a href="[field:arcurl/]" target="_blank" title="[field:title/]">[field:title/] ...</a></span>
                  <span class="rel">[field:pubdate runphp='yes'] $today = Floor(time()/(3600 * 24)); $senday= Floor(@me/(3600 * 24)); $updays = $today-$senday; if($updays==0) @me = "今日"; else @me = $updays."天前"; [/field:pubdate]<span class="glyphicon glyphicon-eye-open" title="浏览次数"></span>[field:click/]</span>
                </li>