<?php
$z[0]=Array("arcurl","",33,48);
$z[1]=Array("litpic","",90,105);
$z[2]=Array("arcurl","",162,177);
$z[3]=Array("title","",202,216);
$z[4]=Array("title","",218,232);
$z[5]=Array("pubdate"," \$today = Floor(time()/(3600 * 24)); \$senday= Floor(@me/(3600 * 24)); \$updays = \$today-\$senday; if(\$updays==0) @me = \"今日\"; else @me = \$updays.\"天前\"; ",285,485);
$z[5][4]['runphp']="yes";
$z[6]=Array("click","",556,570);

?>