<?php
$z[0]=Array("global","",84,110);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",155,182);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",226,256);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",491,520);
$z[3][4]['name']="cfg_templeturl";
$z[4]=Array("global","",591,620);
$z[4][4]['name']="cfg_templeturl";
$z[5]=Array("global","",705,734);
$z[5][4]['name']="cfg_templeturl";
$z[6]=Array("global","",807,836);
$z[6][4]['name']="cfg_templeturl";
$z[7]=Array("global","",888,917);
$z[7][4]['name']="cfg_templeturl";
$z[8]=Array("global","",1032,1061);
$z[8][4]['name']="cfg_templeturl";
$z[9]=Array("global","",1085,1111);
$z[9][4]['name']="cfg_webname";
$z[10]=Array("arclist","\r\n                	<li><a href=\"[field:arcurl/]\" target=\"_blank\" title=\"[field:title/]\">[field:title/]...</a></li>\r\n                   ",3970,4167);
$z[10][4]['row']="5";
$z[10][4]['titlelen']="50";
$z[10][4]['typeid']="2";
$z[11]=Array("arclist","\r\n                  <div class=\"swiper-slide\">\r\n                    <a href=\"[field:arcurl/]\" target=\"_blank\">\r\n                    <img src=\"[field:litpic/]\" alt=\"[field:title/]\" />\r\n                    <p>网站设计<br /><strong>[field:title/]</strong><br />[field:id function=GetTags(@me)/]</p></a>\r\n                  </div>\r\n                  ",5847,6258);
$z[11][4]['row']="3";
$z[11][4]['titlelen']="30";
$z[11][4]['typeid']="1";
$z[12]=Array("global","",13718,13747);
$z[12][4]['name']="cfg_templeturl";
$z[13]=Array("global","",14802,14831);
$z[13][4]['name']="cfg_templeturl";

?>