<?php
$z[0]=Array("global","",340,369);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("global","",434,463);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",523,552);
$z[2][4]['name']="cfg_templeturl";
$z[3]=Array("global","",633,662);
$z[3][4]['name']="cfg_templeturl";
$z[4]=Array("global","",735,764);
$z[4][4]['name']="cfg_templeturl";
$z[5]=Array("global","",816,845);
$z[5][4]['name']="cfg_templeturl";
$z[6]=Array("global","",949,978);
$z[6][4]['name']="cfg_templeturl";

?>