<?php
$z[0]=Array("field","",84,103);
$z[0][4]['name']="title";
$z[1]=Array("global","",104,130);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",175,197);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",241,292);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",523,552);
$z[4][4]['name']="cfg_templeturl";
$z[5]=Array("global","",617,646);
$z[5][4]['name']="cfg_templeturl";
$z[6]=Array("global","",731,760);
$z[6][4]['name']="cfg_templeturl";
$z[7]=Array("global","",833,862);
$z[7][4]['name']="cfg_templeturl";
$z[8]=Array("global","",914,943);
$z[8][4]['name']="cfg_templeturl";
$z[9]=Array("global","",998,1027);
$z[9][4]['name']="cfg_templeturl";
$z[10]=Array("global","",1176,1205);
$z[10][4]['name']="cfg_templeturl";
$z[11]=Array("global","",1312,1341);
$z[11][4]['name']="cfg_templeturl";
$z[12]=Array("channel","\r\n            <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n            ",1583,1805);
$z[12][4]['type']="top";
$z[12][4]['currentstyle']="<li class='active'><a href='~typelink~' style='color:white;'>~typename~</a></li>";
$z[13]=Array("channel","\r\n        	 <a href=\"[field:typeurl/]\" class=\"btn btn-default\">[field:typename/]</a>\r\n             ",2388,2614);
$z[13][4]['type']="son";
$z[13][4]['currentstyle']="<a href='~typelink~' class='btn btn-default btn-primary'>~typename~</a>";
$z[14]=Array("list","\r\n        	<li>\r\n              <a href=\"[field:arcurl/]\" target=\"_blank\">\r\n              <img src=\"[field:litpic/]\" alt=\"[field:title/]\" />\r\n              <p>网站设计<br /><strong>[field:title/]</strong><br />[field:id function=GetTags(@me)/]</p></a>\r\n            </li>\r\n           ",2747,3070);
$z[14][4]['pagesize']="12";
$z[15]=Array("pagelist","",3188,3244);
$z[15][4]['listitem']="pre,next,pageno";
$z[15][4]['listsize']="5";

?>