<?php
$z[0]=Array("global","",358,387);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("global","",452,481);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",566,595);
$z[2][4]['name']="cfg_templeturl";
$z[3]=Array("global","",668,697);
$z[3][4]['name']="cfg_templeturl";
$z[4]=Array("global","",746,775);
$z[4][4]['name']="cfg_templeturl";
$z[5]=Array("global","",899,928);
$z[5][4]['name']="cfg_templeturl";

?>